name: Analyze

inputs:
  testFramework:
    description: 'Test Framework'
    default: ''
    required: true
    type: string
  configuration:
    description: 'configuration'
    default: ''
    required: true
    type: string
  powerShellPlatform:
    description: 'PowerShell Platform'
    default: ''
    required: true
    type: string
  IsGenerateBased:
    description: 'target to generation branch?'
    default: ''
    required: true
    type: string
  
runs:
  using: 'composite'
  steps:
    - name: Check - print context
      shell: pwsh
      env: 
          job: ${{ toJson(job) }}
      run: |
        Write-Host "----------------------------- 1"
        Write-Host $env:job
        Write-Host "----------------------------- 2"
