# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: pool-windows-2019

steps:

- task: PowerShell@2
  displayName: 'Install platyPS'
  inputs:
    targetType: 'inline'
    script: 'Install-Module platyPS -Force -Confirm:$false -Scope CurrentUser'
    pwsh: true