name: PR-Validation-powershell-core
on:
  pull_request:

env:
  TestFramework: net6.0
  TestTarget: Test
  Configuration: Debug
  DebugLocalBuildTasks: true
  IsGenerateBased: ${{ startsWith(github.base_ref, 'generation') }}
  BuildTimeoutInMinutes: 120
  AnalysisTimeoutInMinutes: 120
  TestTimeoutInMinutes: 180
  BuildAzPredictor: false
  EnableTestCoverage: true
  TestCoverageLocation: 'artifacts'
  PowerShellPlatform: 'PowerShell Core'
  AZURE_CLIENTS_SHOW_SECRETS_WARNING: true
  
jobs:

  Build:
    uses: ./.github/workflows/pr-build-steps.yml
    with:
      configuration: 'Debug'
      testFramework: 'net6.0'
      powerShellPlatform: 'PowerShell Core'
  Analyze:
    needs: Build
    uses: ./.github/workflows/pr-analyze-steps.yml
    with:
      configuration: 'Debug'
      testFramework: 'net6.0'
  Test:
    needs: Build
    uses: ./.github/workflows/pr-test-steps.yml
    with:
      configuration: 'Debug'
      testFramework: 'net6.0'
      testTarget: 'Test'
