name: PR Build

on:
  workflow_call:
    inputs:
      testFramework:
        description: 'Test Framework'
        default: ''
        required: true
        type: string
      configuration:
        description: 'configuration'
        default: ''
        required: true
        type: string
      powerShellPlatform:
        description: 'PowerShell Platform'
        default: ''
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check - print context
      shell: pwsh
      env: 
          inputs: ${{ toJson(inputs) }}
          github: ${{ toJson(github) }}
      run: |
        Write-Host "----------------------------- 1"
        Write-Host $env:inputs
        Write-Host "----------------------------- 2"
        Write-Host $env:github
        Write-Host "----------------------------- 3"
    - name: List PR Changed Files
      uses: ./.github/workflows/get-pr-changed-files
    - name: Check - Print Content of FilesChanged
      shell: pwsh
      run: |
        Get-Content .\artifacts\FilesChanged.txt
    - name: Install Autorest & Setup environment for Autorest
      if: ${{ env.IsGenerateBased == 'true' }}
      shell: pwsh
      run: |
        npm install autorest@latest
        $env:NODE_OPTIONS=\"--max-old-space-size=65536\"
    - name: Check Ignored File
      shell: pwsh
      run: |
        ./tools/CheckIgnoredFile.ps1
    - name: Set .Net SDK Version
      uses: ./.github/workflows/set-dotnet-sdk-version
      with:
        version: '6.0.x'
    - name: Build
      shell: pwsh
      run: |
        dotnet msbuild build.proj /t:Build /p:'Configuration=${{ inputs.configuration }};TestFramework=${{ inputs.testFramework }};PullRequestNumber=${{ github.event.number}}'
    - name: Save ${{ inputs.testFramework }}
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with: 
        name: build-${{ inputs.testFramework }}
        path: artifacts
